version: '3'

services:
    fastapi:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - .:/app
            - /app/.venv
        environment:
            REDIS_PASS: "Redis2024!"
            REDIS_HOST: "redis"
            REDIS_PORT: "6379"
        command:
            [
                "poetry",
                "run",
                "uvicorn",
                "--host",
                "0.0.0.0",
                "--port",
                "8000",
                "app.main:app",
                "--reload",
            ]
    redis:
        image: redis/redis-stack:7.2.0-v10
        command: [ "/entrypoint.sh", "./redis-stack.conf" ]
        ports:
        - "6379:6379"
        restart: unless-stopped
